In [25]:
import numpy as np
A=np.random.randint(low=3,high=10,size=(2,3))
print("A:",A)
print("shape:",A.shape)
np.array([1,2,3])+10
B=np.random.randint(low=2,high=20,size=(2,3))
print("B:",B)
print("A+B",A+B)


A: [[5 6 8]
 [5 7 6]]
shape: (2, 3)
B: [[10 13  8]
 [18 18  2]]
[[15 19 16]
 [23 25  8]]


In [19]:
import numpy as np
A=np.array([3,11,4,5])
B=np.array([5,0,3])
A[:, np.newaxis]
B[np.newaxis, :]
A[:, np.newaxis] - B[np.newaxis, :]


array([[-2,  3,  0],
       [ 6, 11,  8],
       [-1,  4,  1],
       [ 0,  5,  2]])

In [ ]:
#RESHAPE
import  numpy as np
foo = np.arange(start=1, stop=9)
print(foo)
f=np.reshape(a=foo, newshape=(2,4))
print(f)
f=np.arange(start=1,stop=5)
ff=f.reshape(2,2)
print(ff)

[1 2 3 4 5 6 7 8]
[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]]


In [ ]:
b = np.array([[1,2,3,4], [5,6,7,8]])
print(b)
print(b.T)

[[1 2 3 4]
 [5 6 7 8]]
[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [ ]:
f1 = np.array([
[3, 9, 7],
[2, 7, 3],
[3, 3, 1]
])
m = f1 == 3 #true at 3 only
print(m)
print(f1[m])
f1[m]=0   #replacing 3 with 0
print(f1)
print(m)

[[ True False False]
 [False False  True]
 [ True  True False]]
[3 3 3 3]
[[0 9 7]
 [2 7 0]
 [0 0 1]]
[[ True False False]
 [False False  True]
 [ True  True False]]


In [ ]:
a = np.array([
[3, 9, 7],
[2, 0, 3],
[3, 3, 1]
])
r=np.array([True,False,True])
s=np.array([False,False,True])
print("1st,3rd rows:",a[r])
print("3rd row:",a[s])
print(a[r,s])  # NumPy uses corresponding indices from each index array
# to select elements from the target array([0,2][,2])-->([0,2][2,2])

1st,3rd rows: [[3 9 7]
 [3 3 1]]
3rd row: [[3 3 1]]
[7 1]


In [ ]:
b1 = np.array([False, False, True, True])
b2 = np.array([False, True, False, True])
a=b1 & b2
b=b1 | b2
c=b1 ^ b2
print(a,"\n",b,"\n",c)
~np.array([False,True])

[False False False  True] 
 [False  True  True  True] 
 [False  True  True False]


array([ True, False])

**INFINITY**

In [ ]:
a=np.array([np.inf, np.NINF])
print(a)
np.array([-1, 1])/0

[ inf -inf]


<ipython-input-46-8a26214f73c3>:3: RuntimeWarning: divide by zero encountered in divide
  np.array([-1, 1])/0


array([-inf,  inf])

**NaN**

In [ ]:
bot = np.ones(shape = (3, 4))
bot[[0, 2], [1, 2]] = np.nan
print(bot)
print(bot == np.nan)

[[ 1. nan  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1. nan  1.]]
[[False False False False]
 [False False False False]
 [False False False False]]


In [ ]:
print(np.nan == np.nan )
np.nan != np.nan

False


True

To see which elements are NaN..

In [ ]:
np.isnan(bot)

array([[False,  True, False, False],
       [False, False, False, False],
       [False, False,  True, False]])

**Generators**

In [ ]:
r = np.random.default_rng()
print(r)
r = np.random.default_rng(12345)
print(r)

Generator(PCG64)


In [11]:
#Integers in the range with repetition
g = np.random.default_rng(seed=123)
g.integers(low=1, high=7, size=6)

array([1, 5, 4, 1, 6, 2])

In [ ]:
#Integers in the range without repetition
g = np.random.default_rng(seed=123)
g.choice(a=20, size=3, replace=False)

array([11, 12,  0])

In [ ]:
# Random Shuffling
a = np.array([
[9, 4],
[3, 8],
[4, 10],
[7, 3],
[5, 10]
])
g = np.random.default_rng(seed=123)
g.permutation(a,axis=0)

array([[ 5, 10],
       [ 9,  4],
       [ 4, 10],
       [ 7,  3],
       [ 3,  8]])

In [12]:
# Uniform generation as 2*3 array
ge = np.random.default_rng(seed=123)
ge.uniform(low=10.4, high=22.3, size=(2, 3))

array([[18.51998717, 11.04047012, 13.02228249],
       [12.59402455, 12.49328022, 20.06392463]])

In [18]:
# Normal distribution
ge= np.random.default_rng(seed=123)
ge.normal(loc=10.0, scale=5, size=(1,2))

array([[5.05439325, 8.16106674]])

In [17]:
# Binomial distribution
ge = np.random.default_rng(seed=123)
ge.binomial(n=10, p=0.30, size=(3,3))

array([[4, 1, 2],
       [2, 2, 4],
       [5, 2, 4]])